app/score_calculator/divide/general_shape.py
tests/test_example.py
tests/test_utils.py

1. 일반형 + 조합룡 파싱 함수를 추가했습니다.
2. 일반형 파싱 함수의 오류를 정상 작동하도록 수정했습니다. (기존 c++ 재귀코드를 stack사용한 python코드로 옮기는 과정에서 생긴 오류)
- 이런식으로 같은 형태가 중복해서 세어졌음
```bash
1m2m3m 1m1m 4m5m6m 7m8m9m 9m9m9m
1m1m 1m2m3m 4m5m6m 7m8m9m 9m9m9m
```
- 파싱 함수 시작부분에 확정된 블럭의 tile(e.g. 후로 블럭)들을 tile리스트에서 제거하는 로직 추가
테스트용 Block, list[Block]을 출력하는 함수를 만들었습니다

add general shape dividing function with knitted blocks and fixed bug

---

app/score_calculator/yaku_check/blocks_yaku_checker.py
pyproject.toml
tests/test_example.py

3블럭으로 구성된 역 체크 함수를 만들었습니다.
두 번 이상 서로 다른 역에서 활용되는 형태의 검증 로직은 ```..._general```형태의 함수로 분리했습니다.
(e.g. ```is_pure_chow_general```은 일색사동순, 일색삼동순, 희상봉에서 동일하게 사용)
중복되는 로직의 함수를 utils 영역에 추가했습니다.
```
count_blocks_if
has_constant_gap
```

add three blocks yaku checker

---

app/score_calculator/yaku_check/blocks_yaku_checker.py
app/score_calculator/yaku_check/hand_yaku_checker.py
app/score_calculator/yaku_check/yaku_checker.py
tests/test_example.py

hand yaku checker에 대한 class를 만들었습니다.
#16 에서 hand에 해당하는 역들을 이 class에 판별할 것입니다.
지금은 숫자 대소비교에 대한 역 5개를 추가했습니다.
(전소/중/대, 소/대우오)
이전까지 만들었던 blocks yaku checker는 1 block을 제외한 역들이 추가되었고  일단 더 이상 추가할 역은 없어 보입니다.
1 block 역들은 blocks yaku checker가 아니라 hand yaku checker 나 winning conditions yaku checker에서 처리하는 쪽으로 하려 합니다. #20 에 적어 놓았습니다.

create hand yaku checker class and add yakus about number compair

---

app/score_calculator/yaku_check/hand_yaku_checker.py
tests/test_example.py

#16 중 hand와 관련된 판별 사항을 가진 4개의 카테고리의 역들을 구현했습니다.
- 사공
- 삼공
- 쌍암공
- 쌍명공
- 암공
- 명공
- 사암각
- 삼암각
- 쌍암각
- 자일색
- 청요구
- 혼요구
- 결일문
- 무자
- 청일색
- 혼일색
- 결일문
---
`@pytest.mark.parametrize`를 이용해 각 yaku에 대한 테스트를 개선했습니다.

add hand yaku about kong, concealed pungs, number conditions and flush

---

app/score_calculator/block/block.py
app/score_calculator/yaku_check/blocks_yaku_checker.py
app/score_calculator/yaku_check/hand_yaku_checker.py
tests/test_example.py

#16 중 hand shape와 관련된 판별 사항을 가진 카테고리의 역들을 구현했습니다.
- 연칠대
- 구련보등
- 일색쌍룡회
- 전쌍각
- 칠대
- 삼색쌍룡회
- 팽팽화
- 평화
`tiles_by_type, num_tile_types_count` 등 중복되어 사용되는 로직이 있거나 lint상 밖으로 로직을 빼야 하는 경우의 유틸리티 method를 `@cached_property`로 구현하였습니다.
`first_tile_numbers`나 `tiles_by_type`등 block yaku checker와 중복되는 유틸리티는 상위 클래스에서 차후 통합하는 식으로 중복을 제거하는게 나아 보입니다.
그 외에 `lambda` 함수 내부 변수명을 `block`이면 `b`, `tile`이면 `t`로 가독성이 좋게 바꾸는 작업을 하였습니다.
`@pytest.mark.parametrize`를 이용해 각 `yaku`에 대한 테스트를 하였습니다.

Add hand shape yakus

---

app/score_calculator/yaku_check/hand_yaku_checker.py
tests/test_example.py

#16 중 대기와 관련된 판별 사항을 가진 카테고리의 역들을 구현했습니다.
- 변장
- 간장
- 단조장
테스트 코드 추가 이슈로 아직 커밋되지 않은 녹일색, 추부도 판별 코드가 없으면 conflict해결이 힘들것 같아(YakuType enum 넘버링 이슈) #25  해당 branch 코드 넣은 상태에서 구현 진행하였습니다.
대기 관련된 역들에 대한 테스트를 하였습니다.
#25 의 역들의 테스트는 구현하지 않았습니다

add yaku check about wait

---

app/score_calculator/result/result.py
app/score_calculator/score_calculator.py
app/score_calculator/utility/utility.py
app/score_calculator/yaku_check/blocks_yaku_checker.py
tests/test_example.py
tests/test_score_calculator_general.py

[![GAME-4](https://badgen.net/badge/JIRA/GAME-4/0052CC)](https://mcrs.atlassian.net/browse/GAME-4) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
일반형에 대한 점수 계산을 구현하였습니다.
먼저, 계산 결과를 저장하는 calss ScoreResult와 점수 계산 과정에서 생기는 context를 저장하는 class ScoringContext가 기존에 설계했던 것과 필요한 내용이 달라져서 수정했습니다.
ScoringContext는 Block들의 관계로 생성되는 역들의 점수 계산에만 관여하게 됐는데, 이름을 바꾸는게 나을지도 모르겠네요.
요구각에 대한 예외처리를 위해 상위역에 대한 set을 만들었습니다
현 로직에서 Pair 조건도 있는 소사희와 소삼원은 blocks yaku checker에서 예외처리 하였습니다.
- general_shape_calculator
현재 일반형만 구현하였습니다, 치또이는 바로 현 코드에 결합가능하고, 불고와 국사는 따로 역 검증 코드를 짜야 합니다.
역을 전부 구하고, 예외처리 역들을 제외하고, 사귀일과 …

GAME-4 add score calculator for general shape

---

app/schemas/game_ws_message.py

[![GAME-30](https://badgen.net/badge/JIRA/GAME-30/0052CC)](https://mcrs.atlassian.net/browse/GAME-30) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
이 PR은 게임 서버와 클라이언트 간 WebSocket 통신에 사용되는 메시지 구조를 통합적으로 관리하기 위해 새로운 스키마 파일(`game_ws_message.py`)을 추가합니다.
- **기본 메시지 모델(BaseGameWebSocketMessage) 추가**  
- `action`과 `data` 필드를 갖도록 정의하여 모든 WebSocket 메시지가 동일한 기본 구조를 따르게 합니다.
- `extra = "forbid"` 옵션을 사용하여, 정의되지 않은 필드가 포함되면 검증 오류를 발생시켜 데이터 무결성을 보장합니다.
- **요청/응답 구분을 위한 액션 타입 정의**  
- 액션 타입에 "authenticateRequest", "authenticateResponse" 를 사용하여 메시지의 역할(클라이언트 요청 vs 서버 응답)을 명확히 구분합니다.
- **액션별 데이터 …

GAME-30 WebSocket 메시지 스키마 통합 구현

---

app/services/game_manager/models/manager.py
app/services/game_manager/models/player.py

[![GAME-15](https://badgen.net/badge/JIRA/GAME-15/0052CC)](https://mcrs.atlassian.net/browse/GAME-15) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
GameManger에서 게임 시작시 init method를 구현했습니다.
Player class의 field에 어떤 것들이 들어갈지는 Core Server에서 넘어오는 정보에 따라 달라지기에, 추후 필드를 추가하고 나서 schemas로 옮길 수 있도록 PlayerDataReceived class를 pydantic BaseModel로 만들었습니다.
roundmanager와 gamemanager의 구조를 약간 바꾸었습니다.
[GAME-15]: https://mcrs.atlassian.net/browse/GAME-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-15 add game start init method

---

app/services/game_manager/models/action.py
app/services/game_manager/models/call_block.py
app/services/game_manager/models/deck.py
app/services/game_manager/models/enums.py
app/services/game_manager/models/hand.py
app/services/game_manager/models/manager.py
app/services/game_manager/models/types.py
tests/test_action_manager.py
tests/test_game_hand.py
tests/test_round_manager.py

[![GAME-20](https://badgen.net/badge/JIRA/GAME-20/0052CC)](https://mcrs.atlassian.net/browse/GAME-20) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
- `Tsumo` 기능을 `RoundManager`에 추가했습니다.
- `enums.py` 등 일부 모듈에서 순환 참조 문제가 발생하지 않도록, `TYPE_CHECKING`을 사용하도록 하였고 파일을 `enums.py`와 `types.py`로 분리하는 방식으로 리팩토링했습니다.
- **RoundManager**:
- `do_tsumo(previous_turn_type: TurnType)` 메서드를 구현하여,  
이전 턴에 따라 타일을 패산의 왼쪽이나 오른쪽에서 뽑고(`draw_tiles`), 손패에 적용한 뒤  
`Winning Condition`을 설정하도록 했습니다.
- `proceed_next_turn` 함수에서, 이전 Turn이나 Action에 따라 Tsumo가 필요한 상황에서 `do_tsumo`를 호출하고, Discard가 필요한 상황에서 `do_discard`를 …

GAME-20: Implement tsumo function and refactor files

---

app/core/network_service.py
app/dependencies/network_service.py
app/services/game_manager/models/manager.py

[![GAME-41](https://badgen.net/badge/JIRA/GAME-41/0052CC)](https://mcrs.atlassian.net/browse/GAME-41) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
Network Manager Class를 만들어서 네트워크 영역의 의존성을 분리하였습니다
지금은 클라쪽 엔드포인트와 연결하는 부분밖에 없긴한데 코어서버측과 연결도 추가할 걸 생각하면 레이어를 나누는게 좋아보여서 이렇게 했습니다
[GAME-41]: https://mcrs.atlassian.net/browse/GAME-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 GAME-41 add network manager class

---

app/schemas/ws.py
app/services/game_manager/models/enums.py
app/services/game_manager/models/manager.py
app/services/game_manager/models/round_fsm.py
tests/test_game_manager.py
tests/test_round_fsm.py
tests/test_round_manager.py

[![GAME-48](https://badgen.net/badge/JIRA/GAME-48/0052CC)](https://mcrs.atlassian.net/browse/GAME-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
FSM에 화료 State(HuState)와 유국 State(DrawState)를 추가했습니다.
Init과정에서 자리 바꾸는 로직을 추가했습니다.
HuState에서 점수 변동 반영하도록 했습니다.
이제 게임 로직적으로는 어느정도 다 한거같습니다
[GAME-48]: https://mcrs.atlassian.net/browse/GAME-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-48 add hu and draw state, fixed init

---

app/api/v1/endpoints/game_websocket_handler.py
app/core/room_manager.py
app/dependencies/game_manager.py
app/dependencies/network_service.py
app/schemas/ws.py
app/services/game_manager/models/hand.py
app/services/game_manager/models/manager.py
app/services/game_manager/models/round_fsm.py
app/services/score_calculator/score_calculator.py
tests/test_game_manager.py
tests/test_round_manager.py

[![GAME-53](https://badgen.net/badge/JIRA/GAME-53/0052CC)](https://mcrs.atlassian.net/browse/GAME-53) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
Game start event로 유저마다 할당된 index,
Round init event로 배패와 자리,
init flower replacement로 flower tile을 빼고 어떤 tile들을 쯔모했는지, 그리고 4명이 각각 flower tile을 몇 개 뺐는지를
웹소켓으로 받도록 하였습니다
첫 쯔모까지 연동하였습니다. 화면에 받은 event에 맞게 반영하는 UI조정 하면 될것같습니다.
그리고 init flower replacement에서 flower tile을 어떤 순서대로 뺐는지(flower tile을 패산에서 가져와서 또 뺐으면 화면에 보여주는 연출에 따라 어떤 flower tile을 가져왔는지가 필요할수도 있으니)도 주면 좋을것 같습니다.
웹소켓에서 finally disconnet하는 라인을 제거했고,
start game을 하면 task로 실행하도록 하였습니다. …

GAME-53/handle websocket about init haipai, flower and first tsumo

---

app/api/v1/endpoints/game_websocket_handler.py
app/schemas/ws.py
app/services/game_manager/models/hand.py
app/services/game_manager/models/manager.py
tests/test_ws.py

[![GAME-57](https://badgen.net/badge/JIRA/GAME-57/0052CC)](https://mcrs.atlassian.net/browse/GAME-57) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
배패 받고 화패 빼는 페이즈에서 어떤 순서대로 화패를 뺐는지에 대한 정보를 추가로 보내주도록 조정하였습니다.
웹소켓 메세지 방식을 일원화하였습니다.
[GAME-57]: https://mcrs.atlassian.net/browse/GAME-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-57/fix websocket message about init flower replacement

---

app/api/v1/endpoints/game_websocket_handler.py
app/core/room_manager.py
app/schemas/ws.py
app/services/game_manager/models/manager.py
app/services/game_manager/models/round_fsm.py
app/services/game_manager/models/types.py

[![GAME-60](https://badgen.net/badge/JIRA/GAME-60/0052CC)](https://mcrs.atlassian.net/browse/GAME-60) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
이전까지의 게임서버-유니티 클라이언트간 연결된 통신이 게임 서버에서 클라이언트로 정보를 보내는 것 위주였다면
이번 PR에서는 클라이언트에서 메시지를 받는 것에 중점을 두었습니다
통합 테스트 과정에서 fsm구조를 변경하고, 버그를 수정하였습니다
통합 테스트 중이라 pytest는 추가/변경 하지 않았고, 디버그문이 들어간 상태입니다.
[GAME-60]: https://mcrs.atlassian.net/browse/GAME-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-60-receive-client-side-websocket-message

---

app/services/game_manager/models/manager.py

[![GAME-66](https://badgen.net/badge/JIRA/GAME-66/0052CC)](https://mcrs.atlassian.net/browse/GAME-66) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
GAME-66-fix-furo-turn-change
후로 턴 처리하는걸 앞쪽 라인으로 빼니까 턴이 자신으로 바뀌고 나서 후로패에 대한 정보 전송이  이루어져서
항상 source tile이 자신이 되는 버그가 있었습니다
라인 순서 변경하여 수정했습니다
[GAME-66]: https://mcrs.atlassian.net/browse/GAME-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-66-fix-furo-turn-change

---

app/services/game_manager/models/manager.py

[![GAME-64](https://badgen.net/badge/JIRA/GAME-64/0052CC)](https://mcrs.atlassian.net/browse/GAME-64) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
통합 테스트 과정에서 전구인시 화료버튼이 떠야했는데 한번 안 떠서
턴 관리에 문제가 있는가 싶어서 라인 순서 변경했습니다
해봤는데 지금은 문제 없는거 같긴하네요
[GAME-64]: https://mcrs.atlassian.net/browse/GAME-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-64-fixed-bug-in-melded-hand-buttons

---

app/services/game_manager/models/hand.py
app/services/game_manager/models/manager.py
app/services/score_calculator/block/block.py

[![GAME-68](https://badgen.net/badge/JIRA/GAME-68/0052CC)](https://mcrs.atlassian.net/browse/GAME-68) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
손패 후로 블럭 파싱할 때 멘젠 상태가 잘못 초기화되는 버그를 고쳤습니다.
[GAME-68]: https://mcrs.atlassian.net/browse/GAME-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-68-fix-concealed-hand-bug

---

app/services/game_manager/models/manager.py

[![GAME-75](https://badgen.net/badge/JIRA/GAME-75/0052CC)](https://mcrs.atlassian.net/browse/GAME-75) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
손패 전송시 론화료나 창깡화료의 경우 화료패인 그 한 장을 빼놓고 화료 손패를 전송하는 버그를 고쳤습니다.
[GAME-75]: https://mcrs.atlassian.net/browse/GAME-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-75-fix-sending-winning-hand-bug

---

app/api/v1/endpoints/game_websocket_handler.py
app/core/room_manager.py
app/dependencies/game_manager.py
app/services/game_manager/fsm/round_fsm.py
app/services/game_manager/helpers/tenpai_assistant.py
app/services/game_manager/manager.py
app/services/score_calculator/tenpai_calculator.py
tests/test_action_manager.py
tests/test_game_manager.py
tests/test_round_fsm.py
tests/test_round_manager.py

[![GAME-79](https://badgen.net/badge/JIRA/GAME-79/0052CC)](https://mcrs.atlassian.net/browse/GAME-79) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
1. game_manager 서비스의 폴더 구조를 바꾸었습니다.
```
game_manager
├── fsm
│   └── round_fsm.py
├── helpers
│   └── tenpai_assistant.py
├── models
│   ├── action.py
│   ├── call_block.py
│   ├── deck.py
│   ├── enums.py
│   ├── event.py
│   ├── hand.py
│   ├── player.py
│   ├── types.py
│   └── winning_conditions.py
└── manager.py
```
2. 텐파이 패 어시스트 기능을 추가하였습니다.
쯔모할 때, 치/퐁 후로할 때마다(손패가 꽉 찰 때마다) 손패의 모든 패에 대해서 그 패를 버리면 총점이 몇 점이고(화패 미포함), 어떤 역으로 구성되었는지에 …

 GAME-79 add tenpai assistance and fix bug

---

app/services/score_calculator/yaku_check/hand_yaku_checker.py

[![GAME-83](https://badgen.net/badge/JIRA/GAME-83/0052CC)](https://mcrs.atlassian.net/browse/GAME-83) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
쌍밍깡 + 안깡 점수계산 제대로 안되는거 수정했습니다
[GAME-83]: https://mcrs.atlassian.net/browse/GAME-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-83-fix-two-melded-kong-and-concealed-kong-scoring

---

app/services/game_manager/helpers/tenpai_assistant.py

[![GAME-88](https://badgen.net/badge/JIRA/GAME-88/0052CC)](https://mcrs.atlassian.net/browse/GAME-88) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
어시스트에서 이전에 깡을 쳤는지에 대한 flag가 반영되어 영상개화 점수가 더해지는 것을 막았습니다.
지금 깡을 쳐서 화료하지 못했다면 영상개화는 어시스트에 포함되지 않아야 합니다.
[GAME-88]: https://mcrs.atlassian.net/browse/GAME-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GAME-88-fix-replacement-tile-bug-in-assist

---

app/services/game_manager/manager.py

[![GAME-87](https://badgen.net/badge/JIRA/GAME-87/0052CC)](https://mcrs.atlassian.net/browse/GAME-87) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
시간초과와 동시에 타패할 경우 타패와 시간초과로 인한 쯔모기리가 동시 적용되는 버그가 있었습니다.
action id 기반으로 timeout시 강제 타패 메세지가 전송되고 나서 action id가 증가하는것을 이용하여 플레이어의 타패 action을 받았을 때 action_id가 현재 acition_id와 다르다면 무시하는 방식으로 처리하였습니다.
[![UNITY-158](https://badgen.net/badge/JIRA/UNITY-158/0052CC)](https://mcrs.atlassian.net/browse/UNITY-158) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-82 …

GAME-87 fix timeout double discard bug
