app/score_calculator/block/block.py
Block Class의 tile에 대한 설명이 필요하다 생각되어 주석으로 추가했습니다.
그리고 Score Calculator 측면에서는 필요없는 요소인 source tile index를 삭제했습니다.
주석이 괜찮은지 확인 부탁드립니다.
=> Add Comment at Block Class and remove useless attribute

pyproject.toml
asyncio_default_fixture_loop_scope = "session"를
asyncio_default_fixture_loop_scope = "function"으로 변경합니다.
이전에 db테스트하기 위한 세팅이었는데, 일단 변경합니다.
나중에 db 테스트필요하거나 하면 그때가서 고민.
=> fix test settings

app/score_calculator/hand/hand.py, app/score_calculator/winning_conditions/winning_conditions.py
Winning Condition에 대한 dataclass를 추가했습니다.
그리고 hand.py에서의 import가 올바르지 않은 파일에서 된 것을 수정했습니다.
=> Add winning conditions class

app/score_calculator/enums/enums.py, app/score_calculator/utility/utility.py, app/score_calculator/winning_conditions/winning_conditions.py, tests/test_utils.py
유틸리티 관련 함수를 모아놓는 utility.py를 만들었습니다.
tests 폴더에 테스트 용도로 test_utils.py를 만들었습니다.
enums.py의 Tile class를 IntEnum으로 바꾸고, 각종 판별 메서드를 넣었습니다.
=> add utilities

app/score_calculator/enums/enums.py, app/score_calculator/hand/hand.py, app/score_calculator/result/result.py, app/score_calculator/utility/utility.py, app/score_calculator/winning_conditions/winning_conditions.py, tests/test_example.py
점수 계산 결과를 담는 result class 추가했습니다.
그외에 역 이름의 enum인 Yaku enum을 추가했습니다.
=> add result and yaku enum

app/score_calculator/block/block.py, app/score_calculator/yaku_check/blocks_yaku_checker.py, tests/test_example.py
=> add 4-blocks yaku checker

README.md, poetry.lock, pyproject.toml
readme file을 수정하고 서버 실행하는 script를 추가했습니다.
=> Fix readme

app/score_calculator/yaku_check/hand_yaku_checker.py
* 녹일색, 추부도를 구현했습니다.
* 테스트코드는 추후에 작성하겠습니다.
=> Add Special Composition Yakus

.github/ISSUE_TEMPLATE/issue-form.yml, .github/workflows/close-jira-issue.yml, .github/workflows/create-jira-issue.yml
[Jira 이슈와 Github 이슈의 연동을 자동화하는 Github Action 추가](https://github.com/MCRMasters/MCR-Masters-Game/pull/32)
jira에서 한글(유니코드)가 들어간 이슈명으로 branch명이 자동생성되어 branch명 변경함
=> [MCR-9] Add GitHub action v0.1.0

.github/ISSUE_TEMPLATE/issue-form.yml
=> MCR-9 fix issue form bug

.github/ISSUE_TEMPLATE/issue-form.yml
=> MCR-9 fix issue form title

.github/workflows/close-jira-issue.yml, .github/workflows/create-jira-issue.yml
=> add permissions on workflows

.github/workflows/create-jira-issue.yml
=> fix subtask typo

.github/workflows/close-jira-issue.yml
fixed bug in close-jira-issue.yml
=> fixed bug in close-jira-issue.yml

tests/test_example.py
녹일색과 추부도의 테스트케이스를 추가했습니다.
기존 코드를 완전히 이해하지 못해서, 일단 복붙하고 일부 내용만 바꾸는 식으로 했는데, 혹시 수정이 필요할까요?
Close #29
=> Add test case of special composition yaku

app/score_calculator/yaku_check/hand_yaku_checker.py, app/score_calculator/yaku_check/winning_conditions_yaku_checker.py, tests/test_example.py
GAME-4 개별 역 검증
add-winning-conditions-yaku-chekcer
화료시 조건에 대한 역 검증 함수 만들기
테스트 함수 구현 완료
Close #59
=> GAME-10 add winning conditions yaku chekcer

app/score_calculator/divide/honors_and_knitted_shape.py, app/score_calculator/divide/seven_pairs_shape.py, app/score_calculator/divide/thirteen_orphans_shape.py, app/score_calculator/enums/enums.py, app/score_calculator/score_calculator.py, app/score_calculator/tenpai_calculator.py, tests/test_tenpai_tiles.py
[![GAME-3](https://badgen.net/badge/JIRA/GAME-3/0052CC)](https://mcrs.atlassian.net/browse/GAME-3) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
- can_divide_honors_and_knitted_shape
- can_divide_thirteen_orphans_shape
- get_tenpai_tiles
- class ScoreCalculator
- 틀만 만들어 놓았고 추가 구현 예정
[GAME-3]: https://mcrs.atlassian.net/browse/GAME-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-3 add tenpai calculator function and score calculator class

app/services/game_manager/models/action.py, app/services/game_manager/models/call_block.py, app/services/game_manager/models/deck.py, app/services/game_manager/models/enums.py, app/services/game_manager/models/hand.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/player.py, app/services/game_manager/models/winning_conditions.py, tests/test_action_manager.py, tests/test_deck.py
[![GAME-19](https://badgen.net/badge/JIRA/GAME-19/0052CC)](https://mcrs.atlassian.net/browse/GAME-19) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
게임 진행에 필요한 데이터 구조와 GameManager, RoundManager class를 정의했습니다.
일단 어떤 필드가 있는지만 정의해놨습니다.
Action 우선순위 판별을 하는 ActionManager는 heapq를 써도 간단해보여서 heapq로 정의했고, 구현을 해야 구조를 설명할 수 있을 것 같아 이 class에 한해서 구현과 테스트까지 했습니다.
Player class는 Core Server에서 어떤 정보를 받아서 어떤 필드에 넣어줘야 할지 잘 모르겠네요. 일단 임시로 정의해놨는데 조언해주시면 감사하겠습니다.
패산 어딨냐 해서 Deck class 따로 분리해서 추가함
[GAME-19]: https://mcrs.atlassian.net/browse/GAME-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> GAME-19 make classes about game management and add Action priority manager

app/services/game_manager/models/deck.py, app/services/game_manager/models/manager.py
[![GAME-17](https://badgen.net/badge/JIRA/GAME-17/0052CC)](https://mcrs.atlassian.net/browse/GAME-17) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
이런식으로 코드를 짜면 변형모드에서 활용을 못할느낌...
docstring을 쓸줄몰라서 간단한 함수 설명은 여기 적습니다
draw_haipai: 패산왼쪽에서 13장을(HAIPAI_TILES) 뽑는함수 -> draw_tiles에서 카운트 관련이 처리 됨
[GAME-17]: https://mcrs.atlassian.net/browse/GAME-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added draw_haipai

app/services/game_manager/models/hand.py, tests/test_game_hand.py
[![GAME-18](https://badgen.net/badge/JIRA/GAME-18/0052CC)](https://mcrs.atlassian.net/browse/GAME-18) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
`GameHand` class에 쯔모, 타패, 치/퐁/소명깡/대명깡/안깡 반영하는 method들 만들었습니다
[GAME-18]: https://mcrs.atlassian.net/browse/GAME-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-18 apply actions to hand

app/services/game_manager/models/hand.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/winning_conditions.py
[![GAME-16](https://badgen.net/badge/JIRA/GAME-16/0052CC)](https://mcrs.atlassian.net/browse/GAME-16) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
RoundManager에 대한 초기화 함수를 구현했습니다.
__init__과 실제 init이 작업이 진행되는 method를 구분하는 것을 목표로 하였습니다.
추후 RoundManager의 구조가 변경되거나 필드가 추가된다면 그에 맞게 수정하면 될 것 같습니다.
[GAME-16]: https://mcrs.atlassian.net/browse/GAME-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-16 Round 초기화 함수 구현

app/services/game_manager/models/action.py, app/services/game_manager/models/enums.py, app/services/game_manager/models/hand.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/types.py, app/services/score_calculator/block/block.py, app/services/score_calculator/enums/enums.py, app/services/score_calculator/hand/hand.py, app/services/score_calculator/winning_conditions/winning_conditions.py, pyproject.toml, tests/test_action_manager.py, tests/test_round_manager.py
[![GAME-31](https://badgen.net/badge/JIRA/GAME-31/0052CC)](https://mcrs.atlassian.net/browse/GAME-31) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
턴 진행(쯔모, 타패, 가깡) 후 가능한 action 체크하는 함수를 만들었습니다.
테스트도 추가했습니다.
[GAME-31]: https://mcrs.atlassian.net/browse/GAME-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-31 add proceed turn and get actions functions and test

app/api/v1/endpoints/game_ws.py, app/core/room_manager.py, app/schemas/ws.py, tests/test_ws_game.py
[![GAME-36](https://badgen.net/badge/JIRA/GAME-36/0052CC)](https://mcrs.atlassian.net/browse/GAME-36) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
core server의 game server 호출하는 함수에 대해 새로운 game id를 생성하고 웹소켓 주소를 반환하는 함수를 만들었습니다
[GAME-36]: https://mcrs.atlassian.net/browse/GAME-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-36 game start api with core

app/api/v1/endpoints/game_websocket_handler.py, app/core/room_manager.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/player.py, app/services/score_calculator/hand/hand.py, tests/test_discard_api.py
[![GAME-25](https://badgen.net/badge/JIRA/GAME-25/0052CC)](https://mcrs.atlassian.net/browse/GAME-25) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
타패 검증 후 결과 전송하는 api 만들었습니다
[GAME-25]: https://mcrs.atlassian.net/browse/GAME-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-25 add discard api

app/schemas/ws.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/round_fsm.py, pyproject.toml, tests/test_round_fsm.py, tests/test_round_manager.py, tests/test_round_manager_2.py
[![GAME-40](https://badgen.net/badge/JIRA/GAME-40/0052CC)](https://mcrs.atlassian.net/browse/GAME-40) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
FSM 아키텍처로 코드를 리팩토링하였습니다.
현재 기본적인 틀만 짜 놓은 상태이고, 미구현상태인 몇몇 state는 TODO를 붙여 놓았습니다.
상태에 대한 정의와 상태 정의를 바탕으로 설계하였습니다.
정리한 결과 게임 루프에 해당하는 코드가 단순해졌습니다
```
async def run_round(self) -> None:
state: RoundState | None = InitState()
while state is not None:
state = await state.run(self)
async def start_game(self) -> None:
for _ in range(self.TOTAL_ROUNDS):
await self.round_manager.run_round()
await self.submit_game_result()
```
기존 구조와 맞지 않아 round …
=> GAME-40 changed game system to FSM structure

app/services/game_manager/models/manager.py, tests/test_round_manager.py
[![GAME-44](https://badgen.net/badge/JIRA/GAME-44/0052CC)](https://mcrs.atlassian.net/browse/GAME-44) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
visible tile list에 action의 결과(치, 퐁, 깡, 타패)가 반영되도록(화절장 조건 체크 위함) 하였습니다.
action에 따른 자리 조정 코드를 넣었습니다.
outdated 주석, 메서드 제거했습니다
[GAME-44]: https://mcrs.atlassian.net/browse/GAME-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-44-apply-action-result-to-visible-tiles-and-fix-comments

app/services/game_manager/models/manager.py, app/services/game_manager/models/round_fsm.py, tests/test_round_fsm.py
[![GAME-55](https://badgen.net/badge/JIRA/GAME-55/0052CC)](https://mcrs.atlassian.net/browse/GAME-55) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
룰북상 오야가 처음부터 14장 가져와야 해서 그거 반영했습니다.
=> GAME-55/fix bug about dealer init tsumo

app/services/game_manager/models/hand.py
[![GAME-58](https://badgen.net/badge/JIRA/GAME-58/0052CC)](https://mcrs.atlassian.net/browse/GAME-58) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
배패단계의 화패 뺄 때의 로직 오류 수정
[GAME-58]: https://mcrs.atlassian.net/browse/GAME-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-58-fix-bug-about-init-haipai-flower

app/schemas/ws.py, app/services/game_manager/models/manager.py
[![GAME-59](https://badgen.net/badge/JIRA/GAME-59/0052CC)](https://mcrs.atlassian.net/browse/GAME-59) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
웹소켓 메세지 보내는 함수 일부 수정
=> GAME-59-refactor-websocket-message

app/api/v1/endpoints/game_websocket_handler.py, app/schemas/ws.py, app/services/game_manager/models/hand.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/types.py
[![GAME-62](https://badgen.net/badge/JIRA/GAME-62/0052CC)](https://mcrs.atlassian.net/browse/GAME-62) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
이번 PR에서는 액션에 대한 선택지를 클라이언트에 넘겨주고, 선택된 액션을 잘 받는 것을 중점으로 작업하였습니다.
이벤트의 유효성 검사도 구현하였습니다.
그 외에 타패에 대한 통신등에서 미구현된 부분을 더 보강하였습니다
[GAME-62]: https://mcrs.atlassian.net/browse/GAME-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-62-add-action-websocket-handler

app/api/v1/endpoints/game_websocket_handler.py, app/services/game_manager/models/enums.py, app/services/game_manager/models/hand.py, app/services/game_manager/models/manager.py, app/services/score_calculator/enums/enums.py, app/services/score_calculator/hand/hand.py
[![GAME-61](https://badgen.net/badge/JIRA/GAME-61/0052CC)](https://mcrs.atlassian.net/browse/GAME-61) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
중간에 실수로 PR 안한부분 PR합니다
IntEnum관련 버그가 있어서 수정하였습니다.
`Task finished with exception: 'int' object has no attribute 'is_flower'`
=> GAME-61-add-action-event-validation

app/schemas/ws.py, app/services/game_manager/models/call_block.py, app/services/game_manager/models/manager.py
[![GAME-63](https://badgen.net/badge/JIRA/GAME-63/0052CC)](https://mcrs.atlassian.net/browse/GAME-63) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
클라이언트와 웹소켓 통신을 통한 통합 테스트를 대략 완성했습니다
통신 더 깔끔히 리팩토링하고 버그 수정 위주로 하면 될 것 같습니다
[GAME-63]: https://mcrs.atlassian.net/browse/GAME-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-63-websocket-client-integration-done

app/api/v1/endpoints/game_ws.py, app/core/config.py, app/services/game_manager/models/manager.py
[![GAME-69](https://badgen.net/badge/JIRA/GAME-69/0052CC)](https://mcrs.atlassian.net/browse/GAME-69) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
화절장이 3장째 패에서 적용되는 버그 수정
점수에 화패 적용 추가
[GAME-69]: https://mcrs.atlassian.net/browse/GAME-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-69 fix last kind tile bug, flower point applying

app/core/config.py, app/schemas/ws.py, app/services/game_manager/models/manager.py
[![GAME-70](https://badgen.net/badge/JIRA/GAME-70/0052CC)](https://mcrs.atlassian.net/browse/GAME-70) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
자리 매핑, 유국 시 화패 처리, 게임 종료시 코어 서버 결과 전송 등을 구현하였습니다.
[GAME-70]: https://mcrs.atlassian.net/browse/GAME-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-70 fix bugs

app/api/v1/endpoints/score_check.html, app/services/score_calculator/score_calculator.py
[![GAME-71](https://badgen.net/badge/JIRA/GAME-71/0052CC)](https://mcrs.atlassian.net/browse/GAME-71) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
점수 테스트 html 경로 수정하였습니다.
오문제 치또이 카운트 안되는 예외 처리하였습니다.
[GAME-71]: https://mcrs.atlassian.net/browse/GAME-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Game 71 fix all type seven pairs bug

app/api/v1/endpoints/game_websocket_handler.py, app/core/room_manager.py, app/main.py, app/services/game_manager/models/manager.py, app/services/game_manager/models/round_fsm.py
[![GAME-73](https://badgen.net/badge/JIRA/GAME-73/0052CC)](https://mcrs.atlassian.net/browse/GAME-73) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
print 디버깅을 로깅으로 바꿨습니다.
[GAME-73]: https://mcrs.atlassian.net/browse/GAME-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Game 73 change print debug to logger

app/api/v1/endpoints/game_websocket_handler.py, app/core/room_manager.py, app/schemas/ws.py, app/services/game_manager/models/manager.py
[![GAME-74](https://badgen.net/badge/JIRA/GAME-74/0052CC)](https://mcrs.atlassian.net/browse/GAME-74) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
연결 해제된 유저 웹소켓을 처리해서 게임 진행에 영향없도 처리했습니다. 재접속하면 등록되는 식으로
[GAME-74]: https://mcrs.atlassian.net/browse/GAME-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-74-disconnected-websocket-control

app/services/game_manager/helpers/tenpai_assistant.py
[![GAME-82](https://badgen.net/badge/JIRA/GAME-82/0052CC)](https://mcrs.atlassian.net/browse/GAME-82) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
화절장 쯔모조건 안되는 버그 수정
[GAME-82]: https://mcrs.atlassian.net/browse/GAME-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-82-last-tile-in-tsumo-bug

app/api/v1/endpoints/game_websocket_handler.py, app/schemas/ws.py, app/services/game_manager/fsm/round_fsm.py, app/services/game_manager/manager.py
[![GAME-86](https://badgen.net/badge/JIRA/GAME-86/0052CC)](https://mcrs.atlassian.net/browse/GAME-86) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
`INIT_EVENT`에서 초기 정보와 flower phase관련 정보까지 한꺼번에 처리하여 flower phase관련 버그가 없도록 하였습니다.
강제 리로드 요청이 들어오면 강제 리로드 데이터를 전송하도록 하였습니다
[GAME-86]: https://mcrs.atlassian.net/browse/GAME-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-86 fix flower phase bug

app/services/game_manager/manager.py
[![GAME-89](https://badgen.net/badge/JIRA/GAME-89/0052CC)](https://mcrs.atlassian.net/browse/GAME-89) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
sry
[GAME-89]: https://mcrs.atlassian.net/browse/GAME-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-89 fix chii pon typo

.gitattributes, .gitignore, app/api/v1/endpoints/watch.py, app/core/room_manager.py, poetry.lock, pyproject.toml
[![GAME-100](https://badgen.net/badge/JIRA/GAME-100/0052CC)](https://mcrs.atlassian.net/browse/GAME-100) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=MCRMasters&utm_campaign=badge_info)
* watch task와 그냥 game task에 대해 종료된 경우 cleanup 메서드 추가하여 메모리 누수 방지(예외로 종료된 경우에 대한 예외처리)
* 모든 플레이어의 연결이 끊긴 경우 게임 task 종료 옵션 추가(무량공처 안되게 일단 처리, 랭겜 나오면 수정해야함-사람 없어도 계속 쯔모기리라도 해야하니까)
* record_event에 대한 로직수정, 일단 모든 event에 대해서 5분딜레이로 watchers에게 보내도록함
* db와 연동된걸로 차후 수정필요
* 기존 잘못된 로직수정
[GAME-100]: https://mcrs.atlassian.net/browse/GAME-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAME-100 fix cleanup method about game
